### ISSUE TITLE
Unable to Set IP on Galaxy Note 8, Android 4.2.2

### ISSUE THREAD

**Issue by EnigmaSolved** [seliver/ElpisRemote#1]
I'm super-excited about where Elpis and ElpisRemote development is headed!  :)

I am having trouble though getting ElpisRemote to work.  I gather from https://github.com/seliver/ElpisRemote/commit/1e016ddd5d9439335f75c4de04c54ae81acd5333 that there should be a `Set IP` button, but there is none displayed on my device.  I try changing the IP and then pressing `Done` on the keypad, but that does not seem to have any effect (just endless spinning, and no connection to the server).  I can successfully connect to the computer Elpis is installed on using another, similar app, Panmote (https://play.google.com/store/apps/details?id=com.jkieliszak.panmote&hl=en), so I know the connection is not the issue.

I'm using 1.4.7 and 1.0.1.

Thoughts?

**Comment by EnigmaSolved** [comment]
Followup: I _do_ see `Set IP` on my Moto G (Android 4.4.4). Also, the `Like` button seems to be missing from the Note 8 (Android 4.2.2). I'm in a different location now, so can't test if the Moto G can connect or not. Will update later when I know more.

**Comment by seliver** [comment]
Hello EnigmaSolved. 
I congratulate you as you're the first user to report an issue :) Yey!
As for the "Set IP" button, you can see it by touching on the ip textbox.
Followup: i have got Moto G too, but the 2014 (5.0.2) one.

Can you send a screenshot from your tablet?

**Comment by EnigmaSolved** [comment]
I feel special!  ;)  And in all seriousness I hope that I can be a helpful source of ideas and suggestions for improving ElpisRemote once I've gotten to try it out for a bit.

Here's my screenshot:
![Note 8 Screenshot](http://s10.postimg.org/exi3cnw0p/2015_03_03_17_04_23.png)

I think I remember running into a similar issue with some other apps in the past, where older versions of Android don't support certain special keyboard methods/buttons, and so you have to provide them another way.

**Comment by seliver** [comment]
I see what's happening, the layout is all buggy for higher resolutions. In the meanwhile you'll have to use your moto :/
Of course you're special, you are already contributing with ideas and testing ;)

**Comment by EnigmaSolved** [comment]
My Moto G _does_ work, so I'm getting to enjoy trying ElpisRemote out!  :)  I'm making a list of ideas, suggestions and improvements (some of which I'm sure overlap with things you've already thought of, are already planning).  I'll probably create a separate issue for each, to make it easy for you to assign things to milestones and otherwise tag stuff.

**Comment by seliver** [comment]
Glad it works :) Does streaming works aswell?
Yes, please do create a separate issue for each :)
Thanks!

**Comment by EnigmaSolved** [comment]
Created a new issue for the Streaming feature: https://github.com/seliver/ElpisRemote/issues/2.

**Comment by seliver** [comment]
Just added a new release with a possible solution for this problem. 
Please try it out and see if it works :)

**Comment by EnigmaSolved** [comment]
Cool--will do!  It'll probably be tomorrow (Saturday) before I can get to it.

**Comment by EnigmaSolved** [comment]
I tried it out yesterday on the Note 8, and all the visuals are fixed, but I still can't get it to set the IP.  Tapping `Done` on the Note 8 onscreen keyboard seems to have no effect.  I suspect that the `Done` key might not be triggering the same underlying function that the `Set IP` custom key does (which only appears on the keyboard for newer versions of Android), but that's just a hunch. I think I remember a situation with another app where the app creator had to create a in-app button to achieve what the custom keyboard button was doing, because (presumably) there was no way to trigger what they needed via `Done`.

**Comment by seliver** [comment]
Unfortunately I have no tablet to test, only my moto g.
Check the latest release i just published where i changed the keycode that is catched. It is probable to work now.

**Comment by seliver** [comment]
Have you got it working now?

**Comment by EnigmaSolved** [comment]
Hey, was meaning to get back to you sooner.  I've been out of town and then under the weather.  But I did get to test it out last night and I did not observe any change (ie, the spinner just spins endlessly after tapping `Done` and it never connects). I was able to immediately connect with the same computer in other ways, so my best guess is still that something isn't getting triggered within the app.  

Does it start searching for the IP as soon as data is added/changed in the field, or only when `Set IP`/`Done` is tapped?

I wonder if another way to go about this would be to go ahead and add the ability to save an IP (or list of IP's to choose from, for those who might use ElpisRemote with multiple computers), ie, #3? That might side-step whatever is not working right on the Note 8 (and/or give us more clarity about what's not working).

**Comment by zolsta** [comment]
I'm also running into this problem where I do not see the set IP button.  My keyboard looks like the same as above.  I'm using a Samsung Galaxy Note 2 Running Android version 4.4.2.

What other information do you need?

**Comment by EnigmaSolved** [comment]
@zolsta, let us know what version of ElpisRemote you're using (https://github.com/seliver/ElpisRemote/releases). I've most recently tried 1.0.5, but that still doesn't work on my Note 8.

**Comment by seliver** [comment]
That is strange. Does the default submit button has any effect?
Em 29/05/2015 12:12 da manhã, "Sean Slevin" notifications@github.com
escreveu:

**Comment by EnigmaSolved** [comment]
The only thing that happens for me when I tap the default `Done` button is the keyboard goes away (which is normal), but the loading spinner keeps spinning and no data from Elpis ever loads.

**Comment by seliver** [comment]
Have you tested if the Elpis server is working properly? To do that, try
accessing through a browser on your tablet to this address:
http://elpis-ip:35747/currentsong .
Em 29/05/2015 02:24, "Sean Slevin" notifications@github.com escreveu:

**Comment by EnigmaSolved** [comment]
Yeah, I know it's working because I also test with my Moto G, which ElpisRemote _does_ work on.  But good question! I wanted to be sure of the same (thus my testing with another device). :)  And using my browser on the Note 8 as you described does bring up the song info, so the tablet itself is also able to connect.

**Comment by zolsta** [comment]
I'm running 1.0.5 (just downloaded it today)  I see the same results as Enigma, I click done, the keyboard goes away, and the spinner keeps spinning.  I don't have another phone/tablet to test on, but point my phones browser to the address posted above, I get back html code that includes current song info, so that part seems to be working.  I'm currently running 1.4.9.0 version of Elpis, just fyi.

**Comment by zolsta** [comment]
So as an update, If I switch my keyboard from Samsung keyboard to Swype, I get the SetIP button and it all works fine.  So using another keyboard is a workaround.  Seems to be a problem with the samsung keyboard.

**Comment by seliver** [comment]
Probably samsung keyboard throws different keyboard events, which is strange. Will make a commit of a general catch when will have the time.

**Comment by HellHound1337** [comment]
Also having the setip issue on a samsung note3 as an FYI

**Comment by seliver** [comment]
Checkout this version and tell me if it solves the ip issue: https://github.com/seliver/ElpisRemote/releases/tag/1.0.6

**Comment by HellHound1337** [comment]
WE HAVE A WINNER! (note3) works like a charm!

**Comment by seliver** [comment]
Great!

**Comment by seliver** [comment]
Great! What about you @EnigmaSolved and @zolsta  ?

**Comment by zolsta** [comment]
Just installed the newest version, tested it out and it worked great!  Thanks for your work on this!

**Comment by EnigmaSolved** [comment]
1.0.6 works great now regarding setting the IP! Thanks much!  :)

Do you want to consider #3 as complete now too, since you added the ability to save the IP address? Or did you want to leave that open because you have more planned related to that? I'm cool either way.

**Comment by seliver** [comment]
Great to hear your feedback!

@EnigmaSolved, just closed #3  ;)

**Comment by EnigmaSolved** [comment]
Yeah man! And thanks for all the extra effort you gave this--those of us with the affected devices very much appreciate it! :)

**Comment by seliver** [comment]
:+1:
